shared:
  image: node:24

jobs:
  first-job:
    requires: [~pr, ~commit]
    steps:
      - ls: ls
    environment:
      GIT_SPARCE_CHECKOUT_PATH: "foo bar"
  second-job:
    requires: [first-job]
    steps:
      - ls: ls
  random-job:
    requires: [second-job]
    steps:
      - echo: echo "this is random job."
